import { Link, createFileRoute } from '@tanstack/react-router'
import SectionRule from '../components/SectionRule'

export const Route = createFileRoute('/features')({
  head: () => ({
    meta: [
      { title: 'Features — Stake Dev Tool' },
      {
        name: 'description',
        content:
          'Fast Rust LGS, multi-resolution test view, live event stream, replay and bookmarks, local HTTPS, team sync. Everything the Stake Engine RGS contract needs.',
      },
    ],
  }),
  component: FeaturesPage,
})

const FEATURES = [
  {
    title: 'Fast Rust LGS',
    desc: 'A drop-in /api/rgs/<game>/wallet server. Reads index.json, lookup tables and books_*.jsonl.zst straight from disk. Books are indexed once per mode, with weighted RNG via binary search.',
  },
  {
    title: 'Multi-resolution test view',
    desc: 'Run your game side by side at seven built-in resolutions plus any custom size. Every frame is its own session, so QA sees exactly what players will.',
  },
  {
    title: 'Live event stream',
    desc: 'Server-sent events push every spin to the test view, with per-frame bet history and a last-event strip. The view updates the instant a spin lands.',
  },
  {
    title: 'Force, replay, bookmark',
    desc: 'Pin any (mode, eventId), replay a saved outcome, and keep notable rounds. Min, average and max wins are picked automatically for each mode.',
  },
  {
    title: 'Local HTTPS',
    desc: 'A bundled CA installs into your user trust store. Your game runs on https without browser warnings or manual certificate work.',
  },
  {
    title: 'Team sync',
    desc: 'Share profiles, saved rounds and bookmarks across your team through cloud workspaces, live over SSE.',
  },
  {
    title: 'Math revisions',
    desc: 'Push immutable math snapshots with content-addressed dedup: a books file unchanged between revisions is never re-uploaded. Every push gets an RTP diff against the previous revision.',
  },
  {
    title: 'Replays that never break',
    desc: 'Saved rounds reference (revision, mode, eventId), so a math change never invalidates a bookmark. Replay any recorded round exactly as it happened.',
  },
  {
    title: 'CI push',
    desc: 'Math is generated by simulations, so the real workflow is CI pushing a revision. The CLI authenticates with a scoped API token and uploads only changed blobs.',
  },
]

function FeaturesPage() {
  return (
    <main className="wrap pt-16 pb-8">
      <SectionRule label="crates/lgs · ui/" />
      <h1 className="display mt-12 mb-0 max-w-2xl text-4xl font-bold sm:text-5xl">
        Everything the RGS contract needs, on your machine.
      </h1>
      <p className="mt-6 mb-0 max-w-xl leading-relaxed text-moss">
        The desktop app wraps a production-grade local game server around your
        math files and your front bundle. Point it at a folder; start
        spinning.
      </p>

      <div className="mt-14 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {FEATURES.map((feature) => (
          <article key={feature.title} className="card card-hover p-6">
            <h2 className="m-0 text-[1.02rem] font-semibold">{feature.title}</h2>
            <p className="mt-2.5 mb-0 text-sm leading-relaxed text-moss">{feature.desc}</p>
          </article>
        ))}
      </div>

      <div className="mt-14 flex flex-wrap gap-3">
        <a
          href="https://github.com/simnJS/stake-dev-tool/releases/latest"
          target="_blank"
          rel="noopener noreferrer"
          className="btn btn-primary"
        >
          Download for desktop
        </a>
        <Link to="/cloud" className="btn btn-ghost">
          See the cloud platform
        </Link>
      </div>
    </main>
  )
}
