// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceSummary } from "./WorkspaceSummary";

/**
 * Response to accepting an invite: the workspace the caller now belongs to.
 */
export type AcceptInviteResponse = { workspace: WorkspaceSummary, };
