// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminOverride } from "./AdminOverride";

/**
 * A workspace row on the admin workspaces list. `plan` is the RESOLVED label
 * (what `plan_for` returns, i.e. including any active override's effect), while
 * `override` echoes the raw stored override row (or `null`).
 */
export type AdminWorkspace = { id: string, slug: string, name: string, created_at: string, members: bigint, games: bigint, storage_bytes: bigint, 
/**
 * Resolved plan label: `"unlimited"` (billing disabled), `"free"`, or
 * `"paid"`.
 */
plan: string, 
/**
 * The resolved seat count when the plan is `"paid"` (from the comp override
 * or the subscription); `null` otherwise.
 */
seats: number | null, override: AdminOverride | null, 
/**
 * The Stripe subscription status verbatim (`"active"`, `"past_due"`, …), or
 * `null` when there is no subscription row.
 */
subscription_status: string | null, };
