// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminShare } from "./AdminShare";

/**
 * `GET /api/admin/shares` response wrapper.
 */
export type AdminSharesResponse = { shares: Array<AdminShare>, };
