// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminUserRow } from "./AdminUserRow";

/**
 * `GET /api/admin/users` response wrapper.
 */
export type AdminUsersResponse = { users: Array<AdminUserRow>, };
