// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminWorkspace } from "./AdminWorkspace";

/**
 * `GET /api/admin/workspaces` response wrapper.
 */
export type AdminWorkspacesResponse = { workspaces: Array<AdminWorkspace>, };
