// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DayCount } from "./DayCount";
import type { HostStats } from "./HostStats";

/**
 * `GET /api/admin/overview` — cheap instance-wide totals plus two 30-day series.
 */
export type AdminOverview = { users: bigint, workspaces: bigint, games: bigint, revisions: bigint, share_links: bigint, 
/**
 * `SUM(blobs.size)` across every workspace (deduplicated per workspace).
 */
storage_bytes: bigint, 
/**
 * Lifetime visitor sessions summed over every share link's counter.
 */
sessions_total: bigint, 
/**
 * Lifetime spins summed over every share link's counter.
 */
spins_total: bigint, 
/**
 * Host machine capacity, for scale planning. `None` when the probe fails
 * (unsupported platform, restricted container) — the UI hides the card.
 */
host: HostStats | null, 
/**
 * Per-day new-account counts over the last 30 days (from `users.created_at`).
 */
signups_30d: Array<DayCount>, 
/**
 * Per-day revision-push counts over the last 30 days (`revisions.created_at`).
 */
pushes_30d: Array<DayCount>, };
