// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /api/admin/me` response, and the body of `PUT /api/admin/users/:id/admin`.
 * The nav link in the dashboard is gated on a successful `{is_admin: true}` here
 * (every non-admin gets a 404 from the endpoint instead, so the surface stays
 * hidden).
 */
export type AdminMe = { is_admin: boolean, };
