// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A manual plan override ("comp subscription") on a workspace, as stored. Shown
 * on the admin workspace list regardless of expiry; `plan_for` ignores it once
 * `expires_at` has passed.
 */
export type AdminOverride = { plan: string, expires_at: string | null, note: string | null, };
