// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user row on the admin users list.
 */
export type AdminUserRow = { id: string, email: string, display_name: string, created_at: string, is_admin: boolean, 
/**
 * Number of workspaces this user is a member of.
 */
workspaces: bigint, };
