// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A share link on the admin (cross-workspace) moderation list.
 */
export type AdminShare = { id: string, slug: string, 
/**
 * The public play URL (custom domain preferred, else the platform play
 * domain), or `null` when no play domain is configured on this instance.
 */
url: string | null, workspace_slug: string, game: string, sessions_count: bigint, spins_count: bigint, revoked_at: string | null, created_at: string, };
