// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BillingInterval } from "./BillingInterval";
import type { BillingLimits } from "./BillingLimits";
import type { BillingUsage } from "./BillingUsage";

/**
 * `GET /workspaces/:slug/billing` response.
 */
export type BillingStatusResponse = { 
/**
 * Whether Stripe billing is configured on this instance. `false` → quotas are
 * never enforced and every limit is unlimited.
 */
enabled: boolean, 
/**
 * The resolved plan label: `"free"` (billing enabled, no active subscription
 * — fully usable within the Free limits: solo, 1 revision kept per game,
 * 1 share link capped at 7 days), `"paid"` (an active seat subscription or
 * comp), or `"unlimited"` (billing disabled, self-host).
 */
plan: string, 
/**
 * The seat count backing a `"paid"` plan (the subscription quantity or the
 * comp's seat count). `null` when the plan is not `"paid"`.
 */
seats: number | null, 
/**
 * The subscription status verbatim from Stripe (e.g. `"active"`, `"trialing"`,
 * `"past_due"`, `"canceled"`), or `null` when there is no subscription. A
 * storage-only subscription (no plan) reports the sentinel `"storage_only"`.
 */
status: string | null, 
/**
 * The subscription's billing interval, or `null` when there is no subscription.
 */
interval: BillingInterval | null, 
/**
 * The current billing period's end, or `null` when there is no subscription.
 */
current_period_end: string | null, 
/**
 * Whether the subscription is scheduled to cancel at the end of the current
 * period (Stripe's `cancel_at_period_end`) while its `status` stays `active`.
 * `false` when there is no subscription or it is not scheduled to cancel; the
 * UI surfaces a calm "your plan ends on `current_period_end`" notice when
 * `true`.
 */
cancel_at_period_end: boolean, 
/**
 * Extra storage granted by the add-on, in GiB (`extra_storage_units × 10`).
 * `0` when no storage add-on is active. Already folded into
 * `limits.max_storage_bytes`; surfaced separately so the UI can show it.
 */
extra_storage_gib: bigint, usage: BillingUsage, limits: BillingLimits, };
