// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current resource usage, counted cheaply for the billing page. `storage_bytes`
 * is `SUM(blobs.size)` over the workspace (deduplicated), cached in-process for
 * 60s; `active_share_links` is 0 on instances where the M5 share tables are not
 * yet present.
 */
export type BillingUsage = { members: bigint, storage_bytes: bigint, active_share_links: bigint, };
