// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BillingInterval } from "./BillingInterval";
import type { BillingLimits } from "./BillingLimits";
import type { BillingUsage } from "./BillingUsage";

/**
 * `GET /workspaces/:slug/billing` response.
 */
export type BillingStatusResponse = { 
/**
 * Whether Polar billing is configured on this instance. `false` → quotas are
 * never enforced and every limit is unlimited.
 */
enabled: boolean, 
/**
 * The resolved plan label: `"trial"`, `"solo"`, `"team"`, `"unlimited"`
 * (billing disabled), or `"expired"` (trial lapsed, unpaid — reads still
 * work, writes are blocked with `upgrade_required`).
 */
plan: string, 
/**
 * The subscription status verbatim from Polar (e.g. `"active"`, `"trialing"`,
 * `"past_due"`, `"canceled"`), or `null` when there is no subscription.
 */
status: string | null, 
/**
 * The subscription's billing interval, or `null` when there is no subscription.
 */
interval: BillingInterval | null, 
/**
 * The current billing period's end (subscription) or, on the free trial, when
 * the trial expires. `null` when neither applies.
 */
current_period_end: string | null, usage: BillingUsage, limits: BillingLimits, };
