// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BillingInterval } from "./BillingInterval";
import type { BillingLimits } from "./BillingLimits";
import type { BillingUsage } from "./BillingUsage";

/**
 * `GET /workspaces/:slug/billing` response.
 */
export type BillingStatusResponse = { 
/**
 * Whether Stripe billing is configured on this instance. `false` → quotas are
 * never enforced and every limit is unlimited.
 */
enabled: boolean, 
/**
 * The resolved plan label: `"free"` (billing enabled, no active subscription
 * — reads still work, writes are blocked with `upgrade_required`), `"paid"`
 * (an active seat subscription or comp), or `"unlimited"` (billing disabled,
 * self-host).
 */
plan: string, 
/**
 * The seat count backing a `"paid"` plan (the subscription quantity or the
 * comp's seat count). `null` when the plan is not `"paid"`.
 */
seats: number | null, 
/**
 * The subscription status verbatim from Stripe (e.g. `"active"`, `"trialing"`,
 * `"past_due"`, `"canceled"`), or `null` when there is no subscription. A
 * storage-only subscription (no plan) reports the sentinel `"storage_only"`.
 */
status: string | null, 
/**
 * The subscription's billing interval, or `null` when there is no subscription.
 */
interval: BillingInterval | null, 
/**
 * The current billing period's end, or `null` when there is no subscription.
 */
current_period_end: string | null, 
/**
 * Extra storage granted by the add-on, in GiB (`extra_storage_units × 10`).
 * `0` when no storage add-on is active. Already folded into
 * `limits.max_storage_bytes`; surfaced separately so the UI can show it.
 */
extra_storage_gib: bigint, usage: BillingUsage, limits: BillingLimits, };
