// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Billing cadence chosen at checkout. Serialized lowercase to match the
 * `subscriptions."interval"` `CHECK` constraint.
 */
export type BillingInterval = "monthly" | "yearly";
