// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Effective quota limits for a workspace. `null` on any field means unlimited
 * (self-hosted instances with billing disabled report every field `null`).
 */
export type BillingLimits = { max_members: number | null, max_storage_bytes: bigint | null, max_active_share_links: number | null, max_concurrent_share_sessions: number | null, };
