// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file present in both revisions but with different content.
 */
export type ChangedFile = { path: string, before_hash: string, after_hash: string, before_size: bigint, after_size: bigint, };
