// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileEntry } from "./FileEntry";

/**
 * `POST /workspaces/:slug/games/:game/revisions/check` request body.
 */
export type CheckRequest = { files: Array<FileEntry>, };
