// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BillingInterval } from "./BillingInterval";
import type { PlanId } from "./PlanId";

/**
 * `POST /workspaces/:slug/billing/checkout` request body.
 */
export type CheckoutRequest = { plan: PlanId, interval: BillingInterval, };
