// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /workspaces/:slug/billing/checkout` response: the hosted Stripe checkout
 * URL the browser is redirected to.
 */
export type CheckoutResponse = { checkout_url: string, };
