// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response: the subset of manifest hashes not yet in this workspace's blobs
 * (i.e. the ones the client still has to upload). Lowercase hex, deduped.
 */
export type CheckResponse = { missing: Array<string>, };
