// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One per-mode compliance check. `expected`/`result` are human-formatted
 * strings for direct display; `pass` is the machine verdict.
 */
export type ComplianceCheck = { check: string, label: string, expected: string, result: string, pass: boolean, };
