// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Health of a single dependency the server talks to (database, object store).
 */
export type ComponentStatus = { ok: boolean, error: string | null, };
