// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the global constraint table. Metrics come in three shapes:
 * * single-value metrics fill `value` (e.g. `max_payout_multiplier`);
 * * bet-scaled metrics fill `value2`/`value3` — the value computed at the 2★
 *   and 3★ reference bets (e.g. `max_exposure`, `max_bet_cost`);
 * * range metrics fill `value` and both `limitX_low` bounds (e.g.
 *   `base_volatility`, which must sit inside `[low, high]`).
 *
 * `limit2`/`limit3` are the upper limits (or range highs). `pass2`/`pass3` are
 * the per-star verdicts.
 */
export type ConstraintRow = { key: string, label: string, value: number | null, value2: number | null, value3: number | null, limit2_low: number | null, limit2: number, limit3_low: number | null, limit3: number, pass2: boolean, pass3: boolean, };
