// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileEntry } from "./FileEntry";

/**
 * `POST /workspaces/:slug/games/:game/front-bundles` request body — the full
 * manifest of the front build. `check` (which hashes are missing) reuses the
 * math [`crate::math::CheckRequest`]/[`crate::math::CheckResponse`] pair.
 */
export type CreateFrontBundleRequest = { files: Array<FileEntry>, };
