// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /workspaces/:slug/games/:game/shares` request body. Every field is
 * optional; omitted fields take their default (generated slug, latest revision,
 * latest bundle, public, never expires, 25 concurrent sessions).
 */
export type CreateShareRequest = { 
/**
 * Custom subdomain label. Generated `word-word-nnn` when omitted.
 */
slug: string | null, 
/**
 * Pin a revision number; omit to track the game's latest revision.
 */
revision_number: number | null, 
/**
 * Pin a front bundle; omit to serve the game's latest bundle.
 */
front_bundle_id: string | null, 
/**
 * Optional password (plaintext; hashed with argon2 server-side).
 */
password: string | null, 
/**
 * Expiry as a number of days from now; omit for no expiry.
 */
expires_in_days: bigint | null, 
/**
 * Concurrent visitor-session cap; omit for the default of 25.
 */
max_concurrent_sessions: number | null, 
/**
 * Enable the visitor feedback overlay (written notes + annotations tied to
 * the last played round). Omit for the default of `false`.
 */
feedback_enabled: boolean | null, };
