// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InviteInfo } from "./InviteInfo";

/**
 * Response to invite creation: the secret and its shareable URL, shown once.
 */
export type CreatedInvite = { invite_url: string, token: string, info: InviteInfo, };
