// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileEntry } from "./FileEntry";

/**
 * `POST /workspaces/:slug/games/:game/revisions` request body. `parent_number`
 * enables optimistic concurrency: when set it must equal the current head.
 */
export type CreateRevisionRequest = { message: string, files: Array<FileEntry>, parent_number: number | null, };
