// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateTokenRequest = { name: string, scopes: Array<string>, expires_in_days: bigint | null, };
