// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenInfo } from "./TokenInfo";

/**
 * Response to token creation: the secret is shown exactly once, here.
 */
export type CreatedToken = { token: string, info: TokenInfo, };
