// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One day's bucket in a 30-day series (`signups_30d`, `pushes_30d`). `date` is a
 * `YYYY-MM-DD` calendar day; empty days are present with `count: 0`.
 */
export type DayCount = { date: string, count: bigint, };
