// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `YYYY-MM-DD` calendar day; empty days are present with `count: 0`.
 */
export type DayCount = { date: string, count: bigint, };
