// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `DELETE /workspaces/:slug/documents/:kind/:doc_id` request body. When
 * `base_revision` is given it must equal the current revision (same optimistic
 * rule as `PUT`); omit it to delete unconditionally.
 */
export type DeleteDocumentRequest = { base_revision: number | null, };
