// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a content-lifecycle deletion (a revision or a front bundle): how
 * much storage the blob GC actually reclaimed. `freed_blobs` counts the blob
 * rows removed; `freed_bytes` sums their sizes. Both are 0 when every referenced
 * blob is still shared by another revision or bundle.
 */
export type DeletionResult = { freed_bytes: bigint, freed_blobs: bigint, };
