// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Success body of a delete: the change cursor `seq` the tombstone was assigned.
 */
export type DeleteDocumentResponse = { seq: bigint, };
