// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response to `POST /api/auth/device/code` (RFC 8628 shaped).
 */
export type DeviceCodeResponse = { device_code: string, user_code: string, verification_uri: string, expires_in: bigint, interval: bigint, };
