// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One bucket of a mode's win-multiplier distribution. Membership is
 * `from < m <= to` (the first bucket is `0 < m <= 0.1`; the last, open bucket
 * has `to == null`). The zero payout is excluded entirely (it is `zero_prob`).
 * `count` is the number of distinct payout values in the range.
 */
export type DistBucket = { from: number, to: number | null, count: bigint, probability: number, 
/**
 * `1 / probability` ("1 in N"), or `null` when the bucket is empty.
 */
effective_hit_rate: number | null, 
/**
 * `Σ p·x` over the bucket — the bucket's absolute share of RTP.
 */
rtp_contribution: number, };
