// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The two document kinds. Serialized in `snake_case` to match the database
 * `CHECK` constraint values and the `?kind=` query parameter.
 */
export type DocumentKind = "profile" | "saved_round";
