// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentKind } from "./DocumentKind";

/**
 * SSE `document` event: a document changed. `data` is intentionally not
 * inlined — the client pulls the new state via `?since_seq=` / GET.
 */
export type DocumentEvent = { kind: DocumentKind, doc_id: string, seq: bigint, };
