// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Machine-readable `code` plus a human `message`. `code` is a stable string
 * (e.g. `email_taken`) the UI can branch on; `message` is for humans.
 */
export type ErrorBody = { code: string, message: string, };
