// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorBody } from "./ErrorBody";

/**
 * Wrapper so failures serialize as `{"error": {"code": ..., "message": ...}}`.
 */
export type ErrorResponse = { error: ErrorBody, };
