// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file in a push manifest / revision: its path, content hash, and size.
 * `hash` is a lowercase hex sha256 (64 chars); `size` is bytes.
 */
export type FileEntry = { path: string, hash: string, size: bigint, };
