// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangedFile } from "./ChangedFile";
import type { FileEntry } from "./FileEntry";

/**
 * File-level diff between two revisions ("before" = `:other`, "after" =
 * `:number`).
 */
export type FileDiff = { added: Array<FileEntry>, removed: Array<FileEntry>, changed: Array<ChangedFile>, unchanged: number, };
