// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `POST /api/auth/forgot-password`. Always answered with a uniform 200
 * (no account enumeration).
 */
export type ForgotPasswordRequest = { email: string, };
