// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * SSE `front_pushed` event: a new front bundle committed for a game (hooked into
 * the M5 front-bundle commit path). The client re-probes the game's front /
 * bundle listing after the nudge.
 */
export type FrontPushedEvent = { game: string, bundle_id: string, };
