// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrontBundleSummary } from "./FrontBundleSummary";

/**
 * `GET /workspaces/:slug/games/:game/front-bundles` response (newest first).
 */
export type FrontBundlesResponse = { bundles: Array<FrontBundleSummary>, };
