// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `201` response after a front bundle commits.
 */
export type FrontBundleCreated = { id: string, created_at: string, };
