// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One front bundle as listed under `GET .../front-bundles` (newest first).
 * `files_count`/`total_size` are derived from the stored manifest JSONB;
 * `is_latest` marks the newest bundle (the one a latest-tracking share serves).
 */
export type FrontBundleSummary = { id: string, created_at: string, files_count: bigint, total_size: bigint, is_latest: boolean, };
