// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A game as listed under `GET /workspaces/:slug/games`.
 */
export type GameSummary = { id: string, slug: string, name: string, 
/**
 * Highest revision number, or `null` when the game has no revisions yet.
 */
head_number: number | null, revisions_count: bigint, created_at: string, };
