// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentStatus } from "./ComponentStatus";
import type { ServiceStatus } from "./ServiceStatus";

/**
 * Response body of `GET /healthz`.
 */
export type HealthResponse = { status: ServiceStatus, version: string, db: ComponentStatus, object_store: ComponentStatus, };
