// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One day's bucket in a 30-day series (`signups_30d`, `pushes_30d`). `date` is a
 * Host machine capacity for the admin overview (scale planning): the disk
 * backing the blob storage and the box's memory.
 */
export type HostStats = { disk_total_bytes: bigint, disk_free_bytes: bigint, mem_total_bytes: bigint, mem_used_bytes: bigint, };
