// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InviteInfo } from "./InviteInfo";

export type InvitesResponse = { invites: Array<InviteInfo>, };
