// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * An invite's metadata. Never carries the secret or its hash.
 */
export type InviteInfo = { id: string, role: Role, created_at: string, expires_at: string, max_uses: number, uses: number, revoked_at: string | null, };
