// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * Public preview shown on the invite-accept page before the visitor signs in.
 */
export type InvitePreview = { workspace_name: string, role: Role, inviter_display_name: string | null, valid: boolean, };
