// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorBody } from "./ErrorBody";

/**
 * The `409 missing_blobs` body: the standard error envelope **plus** a
 * `missing` array of the lowercase-hex hashes that must be uploaded first.
 */
export type MissingBlobsResponse = { error: ErrorBody, missing: Array<string>, };
