// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-mode bet stats derived from a mode's lookup table (weights CSV) alone —
 * no books are read. `cost` is the mode's cost multiplier; `rtp` is
 * `sum(weight * payout) / sum(weight) / cost` (payout being the decimal win
 * multiple, i.e. the CSV column / 100); `max_win` is the largest win multiple;
 * `entries` is the number of lookup rows; `hit_rate` is the share of weight
 * with a non-zero payout.
 */
export type ModeStats = { mode: string, cost: number, rtp: number, max_win: number, entries: bigint, hit_rate: number, };
