// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComplianceCheck } from "./ComplianceCheck";
import type { DistBucket } from "./DistBucket";

/**
 * Per-mode deep-dive. All multipliers are "VS BET" decimal multiples
 * (`m = payout / 100`); cost-normalized quantities use `x = m / cost` so that
 * RTP, `std_dev`, CVaR and the ETLs are all expressed "at cost 1×".
 *
 * `volatility` is a heuristic label off `std_dev`: `< 8` low, `8..=25` medium,
 * `> 25` high. Streak/among-spins fields are `null` in the degenerate cases
 * their closed forms are undefined (e.g. `worst_zero_streak` when a mode never
 * pays zero).
 */
export type ModeAnalysis = { mode: string, cost: number, rtp: number, std_dev: number, volatility: string, max_win: number, min_win: number, zero_prob: number, sub_bet_prob: number, win_prob: number, break_even_miss_prob: number, hit_rate: number, 
/**
 * Distinct payout values, including the zero (losing) payout.
 */
unique_payouts: bigint, entries: bigint, 
/**
 * `1 / P(m == max m)`, i.e. "1 in N" odds of hitting the top multiplier.
 */
max_win_odds: number, avg_spins_any_win: number | null, worst_zero_streak: bigint | null, avg_spins_profit: number | null, worst_loss_streak: bigint | null, tail_prob_5000: number, tail_prob_10000: number, cvar: number, etl_40: number, etl_10000: number, etl_sum: number, distribution: Array<DistBucket>, compliance: Array<ComplianceCheck>, };
