// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModeStats } from "./ModeStats";

/**
 * Before/after stats for a single mode. Either side is `null` when its
 * revision's stats aren't `ok`, or when the mode is absent on that side.
 */
export type ModeStatsDiff = { mode: string, before: ModeStats | null, after: ModeStats | null, };
