// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A purchasable plan. Serialized lowercase to match the `subscriptions.plan`
 * `CHECK` constraint and the Stripe price mapping.
 */
export type PlanId = "solo" | "team";
