// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /workspaces/:slug/billing/portal` response: the Stripe Customer Portal
 * session URL the browser is redirected to. The portal is Stripe-hosted and
 * short-lived (generated per request); it lets a subscriber update their payment
 * method, view invoices, or cancel the subscription.
 */
export type PortalResponse = { url: string, };
