// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One display resolution stored inside a `profile` document. Mirrors the V1
 * desktop `ResolutionPreset`; `enabled`/`builtin` default so older records
 * (and partial payloads) still validate.
 */
export type ProfileResolution = { id: string, label: string, width: number, height: number, enabled: boolean, builtin: boolean, };
