// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileResolution } from "./ProfileResolution";

/**
 * The `profile` document payload (the `data` blob of a `profile` document).
 * Mirrors the V1 `Profile` minus the per-machine `gamePath` and the legacy
 * `teamId`. `game`/`revision` are the loose M2 linkage: a profile may point at
 * a workspace game that has no cloud revisions yet (`revision = null` = latest).
 * Unknown fields are tolerated on write and preserved verbatim in the stored
 * document; the server validates only the fields listed here.
 */
export type ProfileDocument = { name: string, game_slug: string, game: string | null, revision: number | null, front_url: string | null, resolutions: Array<ProfileResolution>, created_at: bigint, };
