// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which sign-in methods this instance offers, for the login page to render.
 */
export type ProvidersResponse = { password: boolean, github: boolean, };
