// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Success body of `PUT /workspaces/:slug/documents/:kind/:doc_id`: the new
 * per-document `revision` and the change cursor `seq` the write was assigned.
 */
export type PutDocumentResponse = { revision: number, seq: bigint, };
