// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `POST /api/auth/reset-password`: a reset token plus the new password.
 */
export type ResetPasswordRequest = { token: string, password: string, };
