// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModeStats } from "./ModeStats";
import type { RevisionAnalysis } from "./RevisionAnalysis";
import type { StatsStatus } from "./StatsStatus";

/**
 * A revision's stats as attached to `RevisionDetail`. `modes` is populated only
 * when `status` is `ok`; `error` carries the reason when `status` is `error`.
 *
 * `analysis` is the full Stake-Engine-style compliance view (2★/3★). It is a
 * sibling of the untouched `modes` array and is present only when `status` is
 * `ok` and the revision has at least one mode. Old stats rows persisted before
 * this field existed deserialize with `analysis == None` (serde default).
 */
export type RevisionStats = { status: StatsStatus, error: string | null, modes: Array<ModeStats>, analysis: RevisionAnalysis | null, updated_at: string, };
