// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatsStatus } from "./StatsStatus";

/**
 * A revision as listed under `GET .../revisions` (newest first).
 */
export type RevisionSummary = { number: number, message: string, author_display_name: string | null, created_at: string, files_count: bigint, total_size: bigint, 
/**
 * `null` until the async stats task has created its row.
 */
stats_status: StatsStatus | null, };
