// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileDiff } from "./FileDiff";
import type { StatsDiff } from "./StatsDiff";

/**
 * `GET .../revisions/:number/diff/:other` response.
 */
export type RevisionDiff = { files: FileDiff, stats: StatsDiff, };
