// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * SSE `revision_pushed` event: a new math revision committed (hooked into the
 * M2 commit path).
 */
export type RevisionPushedEvent = { game: string, number: number, };
