// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConstraintRow } from "./ConstraintRow";
import type { ModeAnalysis } from "./ModeAnalysis";

/**
 * Stake-Engine-style compliance analysis for a whole revision: the global
 * constraint table (checked across modes at two reference bet levels), the
 * star grade derived from it, the cross-mode RTP spread, and the per-mode
 * deep-dive ([`ModeAnalysis`]).
 *
 * Star grade: `stars = 3` when every constraint passes its 3★ limit, else `2`
 * when every constraint passes its (stricter) 2★ limit, else `0`. The 3★
 * limits are looser than the 2★ limits (higher-volatility games get more
 * headroom), so a game can be 3★ without being 2★.
 *
 * `reference_max_bet_2`/`reference_max_bet_3` (200 / 1000) are documented
 * stand-ins for Stake's per-game bet-level templates: bet-scaled limits
 * (`max_exposure`, `max_bet_cost`) are evaluated at these bets.
 */
export type RevisionAnalysis = { two_star_compliant: boolean, three_star_compliant: boolean, stars: number, 
/**
 * `max(RTP) − min(RTP)` across modes; Stake expects modes to share an RTP.
 */
cross_mode_rtp_variance: number, 
/**
 * `cross_mode_rtp_variance <= 0.01`.
 */
cross_mode_rtp_pass: boolean, reference_max_bet_2: bigint, reference_max_bet_3: bigint, constraints: Array<ConstraintRow>, modes: Array<ModeAnalysis>, };
