// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModeStats } from "./ModeStats";
import type { StatsStatus } from "./StatsStatus";

/**
 * A revision's stats as attached to `RevisionDetail`. `modes` is populated only
 * when `status` is `ok`; `error` carries the reason when `status` is `error`.
 */
export type RevisionStats = { status: StatsStatus, error: string | null, modes: Array<ModeStats>, updated_at: string, };
