// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileEntry } from "./FileEntry";
import type { RevisionStats } from "./RevisionStats";

/**
 * Full revision view: metadata, its file manifest, and its stats (if any).
 */
export type RevisionDetail = { number: number, message: string, author_display_name: string | null, created_at: string, files: Array<FileEntry>, stats: RevisionStats | null, };
