// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A member's role in a workspace. Serialized lowercase to match the database
 * `CHECK` constraint values.
 */
export type Role = "owner" | "admin" | "member";
