// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `saved_round` document payload. V1 `SavedRound` plus the optional M2
 * revision pin (`revision = null` = "latest at the time"; legacy imports leave
 * it null). Unknown fields are tolerated and preserved.
 */
export type SavedRoundDocument = { game_slug: string, mode: string, event_id: number, description: string, revision: number | null, created_at: bigint, };
