// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Overall service health. `degraded` means at least one component is down.
 */
export type ServiceStatus = "ok" | "degraded";
