// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PUT /api/admin/workspaces/:id/override` request body. `plan: null` deletes the
 * override row; a value upserts it. `expires_in_days` (optional) sets an expiry
 * that many days out; `note` (optional) is free-form provenance.
 */
export type SetOverrideRequest = { 
/**
 * `"paid"`, `"unlimited"`, or `null` (which clears the override).
 */
plan: string | null, 
/**
 * Required when `plan == "paid"` (the comped seat count, `1..=100`); ignored
 * for `"unlimited"`.
 */
seats: number | null, expires_in_days: bigint | null, note: string | null, };
