// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShareLinkView } from "./ShareLinkView";

/**
 * `GET /workspaces/:slug/games/:game/shares` response.
 */
export type ShareLinksResponse = { shares: Array<ShareLinkView>, };
