// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A share link as returned by create/list. `url` is the full
 * `https://<slug>.<play_domain>/` when the instance has a play domain
 * configured, else `null` (a note the dashboard renders instead).
 */
export type ShareLinkView = { id: string, slug: string, url: string | null, 
/**
 * The game slug this link serves (handy for the dashboard's grouping).
 */
game: string, 
/**
 * `null` = tracks the latest revision.
 */
revision_number: number | null, 
/**
 * `null` = serves the latest bundle.
 */
front_bundle_id: string | null, password_protected: boolean, expires_at: string | null, max_concurrent_sessions: number, revoked_at: string | null, created_at: string, sessions_count: bigint, spins_count: bigint, total_bet: number, total_win: number, 
/**
 * `total_win / total_bet` when `total_bet > 0`, else `null`.
 */
observed_rtp: number | null, 
/**
 * Best-effort count of visitor sessions seen in the last 30 min on this
 * node (in-memory; not shared across a multi-node deployment).
 */
active_sessions: bigint, };
