// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle of a revision's computed stats.
 */
export type StatsStatus = "pending" | "ok" | "error";
