// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModeStatsDiff } from "./ModeStatsDiff";

export type StatsDiff = { modes: Array<ModeStatsDiff>, };
