// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /workspaces/:slug/billing/storage` request body: how many storage
 * add-on units to purchase, each granting +10 GiB for €1/mo. Bounded `1..=100`
 * server-side (a single Stripe checkout with `quantity = units`).
 */
export type StorageCheckoutRequest = { units: bigint, };
