// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A personal API token's metadata. Never carries the secret or its hash.
 */
export type TokenInfo = { id: string, name: string, scopes: Array<string>, created_at: string, expires_at: string | null, last_used_at: string | null, revoked_at: string | null, };
