// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PATCH /workspaces/:slug/games/:game/shares/:id` request body.
 *
 * The three nullable-and-optional fields use tri-state JSON semantics: an
 * **absent** key leaves the value unchanged, an explicit **null** clears it
 * (track-latest / remove password / never-expire), and a value sets it.
 */
export type UpdateShareRequest = { 
/**
 * Absent = unchanged, `null` = track latest, `n` = pin revision `n`.
 */
revision_number?: number | null, 
/**
 * Absent = unchanged, `null` = latest bundle, id = pin that bundle.
 */
front_bundle_id?: string | null, 
/**
 * Absent = unchanged, `null` = remove password, string = set new password.
 */
password?: string | null, 
/**
 * Absent = unchanged, `null` = never expire, `n` = expire `n` days from now.
 */
expires_in_days?: bigint | null, 
/**
 * Absent = unchanged; sets the concurrent visitor-session cap.
 */
max_concurrent_sessions: number | null, 
/**
 * Absent = unchanged, `true` = revoke, `false` = un-revoke.
 */
revoked: boolean | null, };
