// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /workspaces/:slug/billing/seats` request body: the new seat count for an
 * already-subscribed workspace. `seats` (bounded `1..=100` server-side, and never
 * below the current member count) becomes the subscription's seat line-item
 * quantity; Stripe prorates the change (`proration_behavior=create_prorations`).
 */
export type UpdateSeatsRequest = { seats: number, };
