// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Public view of an account. Never carries the password hash.
 */
export type User = { id: string, email: string, display_name: string, created_at: string, 
/**
 * Whether the account's email address has been confirmed. Always `true` on
 * instances without email configured, and for provider (GitHub/Discord)
 * logins whose email the provider already verified.
 */
email_verified: boolean, };
