// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";
import type { WorkspaceMember } from "./WorkspaceMember";

/**
 * Full workspace view: the workspace, the caller's role, and every member.
 */
export type WorkspaceDetail = { id: string, slug: string, name: string, created_at: string, role: Role, members: Array<WorkspaceMember>, };
