// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PUT /api/workspaces/:slug/domain` request body and response. `domain: null`
 * clears the workspace's custom play domain; a value sets it (validated +
 * lowercased server-side). The response echoes the stored value.
 */
export type WorkspaceDomain = { domain: string | null, };
