// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * A single member as shown on a workspace detail page.
 */
export type WorkspaceMember = { id: string, display_name: string, role: Role, joined: string, };
