// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceSummary } from "./WorkspaceSummary";

export type WorkspacesResponse = { workspaces: Array<WorkspaceSummary>, };
