// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * A workspace paired with the calling user's role in it.
 */
export type WorkspaceSummary = { id: string, slug: string, name: string, role: Role, created_at: string, };
